name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
        
    - name: Install dependencies
      run: go get .
      
    - name: Build
      run: go build -v ./...
      
    - name: Test with the Go CLI
      run: go test ./...
      
    - name: Run vet
      run: go vet ./...
      
    - name: Build binary
      run: go build -o bin/sectore cmd/sectore/main.go
      
    - name: Test binary functionality
      run: |
        chmod +x bin/sectore
        ./bin/sectore --help

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m
