name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        
    - name: Install dependencies
      run: go mod download
      
    - name: Build
      run: go build -v ./...
      
    - name: Debugging - Current Directory and Files
      run: |
        pwd
        ls -R
        go env
        
    - name: Test with the Go CLI
      run: go test ./...
      
    - name: Run vet
      run: go vet ./...
      
    - name: Build binary
      run: go build -o bin/sectore cmd/sectore/main.go
      
    - name: Test binary functionality
      run: |
        chmod +x bin/sectore
        ./bin/sectore --help

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Debugging - Check .golangci.yml
      run: ls -la .golangci.yml

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
